### PR TITLE
Update compare todo

### PR DESCRIPTION
**Pull request by dtwrub**
Added and reworded tis description. I think maybe a graphic might be helpful here. I will try to work on a simple one if I have a chance, but LMK what you think of this so far.

### CODE REVIEW

**Comment by daisieh** [comment]
I like where this is going!

**Comment by dmgt** [comment]
This definitely helps clarify this section!

Question - is it possible for someone's branch to be behind, hit the 'Compare' button, and *not* get the **there isn’t anything to compare** message?  If so, I think it'd be helpful to include a line about what to do next in that case. 

Also small typo, line 90: clikcing --> clicking

**Comment by dtwrub** [comment]
Thanks for catching the typo! That's a good question - @daisieh ? I want to say in this specific case, it's unlikely - this is in case you have already forked a repo and haven't done anything with it in a while. I guess it might be possible, if you made some changes to your repo, but didn't push them to the origin?

**Comment by fmichonneau** [comment]
If I follow correctly, I think here you'd want to add how to bring changes from upstream to your repository using the web interface. I have never done this, but I think you'd need to create a pull request using the upstream repository as the head fork and your repository as the base.

**Comment by dmgt** [comment]
Since the Bug BBQ is this weekend, I'm going to merge @dtwrub's improvements for now and open an issue that this part of the explanation can be further improved

**Pull request merged**
